lock again, after reset. see traceback:
❯ VITE_SITE_ID=defis npm run build

> udata-front-kit@0.4.0 build
> vite build

/Users/alexandre/Developer/Ecolab/Ecopshères/ecospheres-front/node_modules/rollup/dist/native.js:64
		throw new Error(
		      ^

Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Users/alexandre/Developer/Ecolab/Ecopshères/ecospheres-front/node_modules/rollup/dist/native.js:64:9)
    at Object.<anonymous> (/Users/alexandre/Developer/Ecolab/Ecopshères/ecospheres-front/node_modules/rollup/dist/native.js:73:76)
    at Module._compile (node:internal/modules/cjs/loader:1740:14)
    at Object..js (node:internal/modules/cjs/loader:1905:10)
    at Module.load (node:internal/modules/cjs/loader:1474:32)
    at Function._load (node:internal/modules/cjs/loader:1286:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:234:24)
    at cjsLoader (node:internal/modules/esm/translators:271:5)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:204:7) {
  [cause]: Error: Cannot find module '@rollup/rollup-darwin-arm64'
  Require stack:
  - /Users/alexandre/Developer/Ecolab/Ecopshères/ecospheres-front/node_modules/rollup/dist/native.js
      at Function._resolveFilename (node:internal/modules/cjs/loader:1410:15)
      at defaultResolveImpl (node:internal/modules/cjs/loader:1061:19)
      at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1066:22)
      at Function._load (node:internal/modules/cjs/loader:1215:37)
      at TracingChannel.traceSync (node:diagnostics_channel:322:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:234:24)
      at Module.require (node:internal/modules/cjs/loader:1496:12)
      at require (node:internal/modules/helpers:135:16)
      at requireWithFriendlyError (/Users/alexandre/Developer/Ecolab/Ecopshères/ecospheres-front/node_modules/rollup/dist/native.js:46:10)
      at Object.<anonymous> (/Users/alexandre/Developer/Ecolab/Ecopshères/ecospheres-front/node_modules/rollup/dist/native.js:73:76) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/Users/alexandre/Developer/Ecolab/Ecopshères/ecospheres-front/node_modules/rollup/dist/native.js'
    ]
  }
}

Node.js v23.5.0